bf16: true
cutoff_len: 2048
dataset: mdd_5k
dataset_dir: data
ddp_timeout: 180000000
do_train: true
enable_thinking: false
eval_steps: 10
eval_strategy: steps
finetuning_type: lora
flash_attn: auto
gradient_accumulation_steps: 8
include_num_input_tokens_seen: true
learning_rate: 5.0e-05
logging_steps: 1
lora_alpha: 16
lora_dropout: 0
lora_rank: 8
lora_target: all
lr_scheduler_type: cosine
max_grad_norm: 1.0
max_samples: 30
model_name_or_path: Qwen/Qwen3-4B-Base
num_train_epochs: 15.0
optim: adamw_torch
output_dir: saves/Qwen3-4B-Base/lora/train_2026-04-02-18-43-47
packing: false
per_device_eval_batch_size: 2
per_device_train_batch_size: 2
plot_loss: true
preprocessing_num_workers: 16
report_to: none
save_steps: 10
stage: sft
template: qwen
trust_remote_code: true
val_size: 0.03
warmup_steps: 0
